server:
  port: 8003

#Configuraciones de Spring.
spring:
  jpa:
    show-sql: true
  application:
    name: crud-db #Nombre de la applicacion.
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #Se indica el driver a utilizar.
    url: jdbc:mysql://localhost:3306/springconfig #Se indica la url de la base de datos.
    username: RostenRoss #username de la base de datos.
    password: Kalifa18. #password de la base de datos.
    hikari:
      maximum-pool-size: 10 #cantidad maxima de conexiontes
      connection-timeout: 5000 #número máximo de milisegundos que el cliente espera una conexión desde el grupo de conexiones.
